# Generated by Django 4.2 on 2023-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(blank=True, max_length=100)),
                ('date_of_entry', models.DateField(blank=True)),
                ('date_of_graduation_from_the_educational_institution', models.DateField(blank=True)),
                ('document_about_education', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('form_of_education', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EducationPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(blank=True, max_length=100)),
                ('date_of_entry', models.DateField(blank=True)),
                ('date_of_graduation_from_the_educational_institution', models.DateField(blank=True)),
                ('retraining_educational_institution', models.CharField(blank=True, max_length=100)),
                ('retraining_specialty', models.CharField(blank=True, max_length=100)),
                ('date_of_entry_retraining', models.DateField()),
                ('date_of_graduation_from_the_retraining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_encouragement', models.CharField(blank=True, choices=[('Дострокове зняття дисциплінарного стягнення', 'Дострокове зняття дисциплінарного стягнення'), ('Занесення на дошку пошани', 'Занесення на дошку пошани'), ('Заохочення грошовою винагородою', 'Заохочення грошовою винагородою'), ('Заохочення цінним подарунком', 'Заохочення цінним подарунком'), ("Надання додаткової плачуваної відпустки тривалістю до п'яти діб", "Надання додаткової плачуваної відпустки тривалістю до п'яти діб"), ('Заохочення відомчими заохочувальними відзнаками Національної поліції України', 'Заохочення відомчими заохочувальними відзнаками Національної поліції України'), ('Заохочення відомчими заохочувальними відзнаками Міністерства внутрішніх справ України', 'Заохочення відомчими заохочувальними відзнаками Міністерства внутрішніх справ України'), ('Дострокове присвоєння чергового спеціального звання', 'Дострокове присвоєння чергового спеціального звання'), ('Присвоєння спеціального звання, вищого на одну ступінь від звання, передбаченого займаною штатною посадою', 'Присвоєння спеціального звання, вищого на одну ступінь від звання, передбаченого займаною штатною посадою'), ("Заохочення відомчою заохочувальною відзнакою Міністерства внутрішніх справа України 'Вогнепальна зброя'", "Заохочення відомчою заохочувальною відзнакою Міністерства внутрішніх справа України 'Вогнепальна зброя'"), ("Заохочення відомчою заохочувальною відзнакою Міністерства внутрішніх справа України 'Холодна зброя'", "Заохочення відомчою заохочувальною відзнакою Міністерства внутрішніх справа України 'Холодна зброя'")], max_length=110)),
                ('order', models.CharField(blank=True, max_length=100)),
                ('date_of_the_order', models.DateField()),
                ('Issuer_of_the_order', models.CharField(blank=True, choices=[('НПУ', 'НПУ'), ('ДПО', 'ДПО'), ('УПО', 'УПО]')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(blank=True, max_length=100)),
                ('father', models.CharField(blank=True, max_length=100)),
                ('wife', models.CharField(blank=True, max_length=100)),
                ('son', models.CharField(blank=True, max_length=100)),
                ('daughter', models.CharField(blank=True, max_length=100)),
                ('date_of_birth_mother', models.DateField(blank=True)),
                ('date_of_birth_father', models.DateField(blank=True)),
                ('date_of_birth_wife', models.DateField(blank=True)),
                ('date_of_birth_son', models.DateField(blank=True)),
                ('date_of_birth_daughter', models.DateField(blank=True)),
                ('place_of_birth_mother', models.CharField(blank=True, max_length=150)),
                ('place_of_birth_father', models.CharField(blank=True, max_length=150)),
                ('place_of_birth_wife', models.CharField(blank=True, max_length=150)),
                ('place_of_birth_son', models.CharField(blank=True, max_length=150)),
                ('place_of_birth_daughter', models.CharField(blank=True, max_length=150)),
                ('position_mother', models.CharField(blank=True, max_length=50)),
                ('position_father', models.CharField(blank=True, max_length=50)),
                ('position_wife', models.CharField(blank=True, max_length=50)),
                ('position_son', models.CharField(blank=True, max_length=50)),
                ('position_daughter', models.CharField(blank=True, max_length=50)),
                ('job_mother', models.CharField(blank=True, max_length=50)),
                ('job_father', models.CharField(blank=True, max_length=50)),
                ('job_wife', models.CharField(blank=True, max_length=50)),
                ('job_son', models.CharField(blank=True, max_length=50)),
                ('job_daughter', models.CharField(blank=True, max_length=50)),
                ('place_of_registration_mother', models.CharField(blank=True, max_length=150)),
                ('place_of_registration_father', models.CharField(blank=True, max_length=150)),
                ('place_of_registration_wife', models.CharField(blank=True, max_length=150)),
                ('place_of_registration_son', models.CharField(blank=True, max_length=150)),
                ('place_of_registration_daughter', models.CharField(blank=True, max_length=150)),
                ('place_of_actual_residence_mother', models.CharField(blank=True, max_length=150)),
                ('place_of_actual_residence_father', models.CharField(blank=True, max_length=150)),
                ('place_of_actual_residence_wife', models.CharField(blank=True, max_length=150)),
                ('place_of_actual_residence_son', models.CharField(blank=True, max_length=150)),
                ('place_of_actual_residence_daughter', models.CharField(blank=True, max_length=150)),
                ('family_camp', models.CharField(choices=[('1', 'Неодружений'), ('2', 'Одружений'), ('3', 'Розлучений')], default='1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FramesPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_private_business', models.IntegerField(blank=True)),
                ('subdivision', models.CharField(choices=[('1', 'Управління поліції охорони'), ('2', 'Краматорське районне відділення'), ('3', "Слов'янське міське відділення"), ('4', 'Бахмутське міжрайонне відділення')], default='1', max_length=5)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Surname', models.CharField(max_length=20)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('special_number', models.IntegerField(blank=True, unique=True)),
                ('sex', models.CharField(max_length=9)),
                ('date_of_recruitment', models.DateField()),
                ('date_of_call_of_the_service', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('city_of_people', models.CharField(max_length=30)),
                ('Archive', models.FileField(blank=True, upload_to='archive/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_position', models.CharField(choices=[('поліцейський взводу реагування', 'поліцейський взводу реагування'), ('поліцейський взводу ОО та ПБ', 'поліцейський взводу ОО та ПБ'), ('поліцейський - водій ВР', 'поліцейський - водій ВР'), ('молодший інспектор взводу ОО та ПБ', 'молодший інспектор взводу ОО та ПБ'), ('молодший інспектор ВР', 'молодший інспектор ВР'), ('інспектор взводу ОО та ПБ', 'інспектор взводу ОО та ПБ'), ('заступник командира взводу', 'заступник командира взводу'), ('командир взводу', 'командир взводу'), ('командир роти', 'командир роти'), ('заступник командира роти', 'заступник командира роти'), ('командир батальйону', 'командир батальйону'), ('заступник командира батальйону', 'заступник командира батальйону')], default='поліцейський взводу ОО та ПБ', max_length=40)),
                ('position_category', models.CharField(choices=[('МНС', 'МНС'), ('НС', 'НС')], default='МНС', max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_order', models.CharField(blank=True, max_length=10)),
                ('Issuer_of_the_order', models.CharField(choices=[('НПУ', 'НПУ'), ('ДПО', 'ДПО'), ('УПО', 'УПО]')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('0', 'рядовий поліції'), ('1', 'капрал поліції'), ('2', 'сержант поліції'), ('3', 'старший сержант поліції'), ('4', 'молодший лейтенант поліції'), ('5', 'лейтенант поліції'), ('6', 'старший лейтенант поліції'), ('7', 'капітан поліції'), ('8', 'майор поліції'), ('9', 'підполковник поліції'), ('10', 'полковник поліції'), ('11', 'генерал поліції 3 рангу')], default='0', max_length=27)),
                ('date_of_the_order', models.DateField()),
                ('order', models.CharField(blank=True, max_length=100)),
                ('Issuer_of_the_order', models.CharField(choices=[('0', 'НПУ'), ('1', 'ДПО'), ('2', 'УПО')], default='2', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_recovery', models.CharField(blank=True, choices=[('Зауваження', 'Зауваження'), ('Догана', 'Догана'), ('Сувора догана', 'Сувора догана'), ('Попередження про неповну посадову відповідність', 'Попередження про неповну посадову відповідність'), ('Пониження у спеціальному званні на одну ступінь', 'Пониження у спеціальному званні на одну ступінь'), ('Звільнення з посада', 'Звільнення з посада'), ('Звільнення зі служби в поліції', 'Звільнення зі служби в поліції')], max_length=50)),
                ('order', models.CharField(blank=True, max_length=100)),
                ('date_of_the_order', models.DateField()),
                ('Issuer_of_the_order', models.CharField(blank=True, choices=[('НПУ', 'НПУ'), ('ДПО', 'ДПО'), ('УПО', 'УПО]')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=10)),
                ('date_of_the_order', models.DateField()),
                ('number_of_days', models.IntegerField(blank=True)),
                ('vacation_start_date', models.DateField()),
                ('vacation_end_date', models.DateField()),
            ],
        ),
    ]
